project:
  type: book
  output-dir: docs

book:
  title: "Cem Deniz SAYINER Progress Journal"
  repo-url: https://github.com/pjournal/mef07-cmdnz
  chapters:
    - index.qmd
    - Assignment 1.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo

